name: Docker report testing variables

on:
  workflow_call:
    inputs:
      artifact-id:
        required: true
        type: string
      artifact-version:
        required: true
        type: string
      is-release:
        required: false
        type: string
      docker-push:
        required: false
        type: boolean

jobs:
  run:
    name: Report testing variables
    runs-on: ubuntu-latest

    steps:
      - name: Show some variables
        env:
          IS_RELEASE: ${{ inputs.is-release }}
          ARTIFACT_ID: ${{ inputs.artifact-id }}
          ARTIFACT_VERSION: ${{ inputs.artifact-version }}
          DOCKER_PUSH: ${{ inputs.docker-push }}
        run: |
          echo "is-release=$IS_RELEASE"
          echo "artifact-id=$ARTIFACT_ID"
          echo "artifact-version=$ARTIFACT_VERSION"
          echo "docker-push=$DOCKER_PUSH"
