name: Go checkout and build

on:
  workflow_call:
    inputs:
      artifact-id:
        required: true
        type: string
      coverage-path:
        required: true
        type: string

jobs:
  run:
    name: Checkout and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Show Go version
        run: go version

      - name: Build the program
        env:
          ARTIFACT_ID: ${{ inputs.artifact-id }}
        run: make "target/$ARTIFACT_ID"

      - name: Run the tests
        run: make test

      - name: Upload coverage reports
        env:
          COVERAGE_PATH: ${{ inputs.coverage-path }}
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: ${{ env.COVERAGE_PATH }}
          if-no-files-found: error
          retention-days: 1
