name: Go linting

on:
  workflow_call:
    inputs:
      lint-golangci-config-file:
        required: false
        type: string
        default: ''
      lint-errcheck-excludes-file:
        required: false
        type: string
        default: ''

jobs:
  golangi:
    name: Lint with golangi
    uses: ./.github/workflows/go-lint-golangci.yml
    with:
      lint-golangci-config-file: ${{ inputs.lint-golangci-config-file }}

  staticcheck:
    name: Lint with staticcheck
    uses: ./.github/workflows/go-lint-staticcheck.yml

  errcheck:
    name: Lint with errcheck
    uses: ./.github/workflows/go-lint-errcheck.yml
    with:
      lint-errcheck-excludes-file: ${{ inputs.lint-errcheck-excludes-file }}
