name: Go lint

on:
  workflow_call:
    inputs:
      lint-errcheck-excludes-file:
        required: false
        type: string

jobs:
  golangci:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        # defaults: gosimple govet ineffassign unused
        with:
          version: v1.61
          args: --disable errcheck --disable staticcheck --enable gosec --issues-exit-code=0

  other-lint:
    name: Lint with others
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install errcheck
        run: go get github.com/kisielk/errcheck@latest
      - name: Run errcheck
        run: |
          if ${{ inputs.lint-errcheck-excludes-file != '' }}; then
            errcheck -exclude ${{ inputs.lint-errcheck-excludes-file }} ./...
          else
            errcheck ./...
          fi
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "2024.1.1"
          install-go: false
