name: Go lint deadcode

on:
  workflow_call:

jobs:
  deadcode:
    name: Lint with deadcode
    runs-on: ubuntu-latest
    steps:
      - name: Run deadcode
        uses: opzkit/godeadcode-action@v1
        with:
          go-version-file: 'go.mod'
