name: Go generate ModuleDescriptor

on:
  workflow_call:
    inputs:
      artifact-id:
        required: true
        type: string
      artifact-version:
        required: true
        type: string
      docker-registry:
        required: true
        type: string

jobs:
  run:
    name: Generate ModuleDescriptor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate ModuleDescriptor
        run: |
          cd target
          VERSION=${{ inputs.artifact-version }} make

      - name: Update LaunchDescriptor
        run: |
          cd target
          mv ModuleDescriptor.json ModuleDescriptor.json.orig
          jq  ". | .launchDescriptor.dockerImage |= \"${{ inputs.docker-registry }}/${{ inputs.artifact-id }}:${{ inputs.artifact-version }}\" | .launchDescriptor.dockerPull |= \"true\"" \
            ModuleDescriptor.json.orig > ModuleDescriptor.json

      - name: Print ModuleDescriptor
        run: cat target/ModuleDescriptor.json

      # we publish it to the registry as a separate job
      - name: Upload ModuleDescriptor as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ModuleDescriptor.json
          path: target/ModuleDescriptor.json

