name: Go Okapi dependency check

on:
  workflow_call:
    inputs:
      okapi-pull-urls:
        required: true
        type: string
    secrets:
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true

jobs:
  run:
    name: Okapi dependency check
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Pull Okapi image
        run: docker pull folioorg/okapi:latest

      - name: Run Okapi
        run: docker run --name okapi -t -detach folioorg/okapi:latest dev

      - id: okapi-ip
        name: Get container IP address
        run: echo "ip=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' okapi)" | tee -a $GITHUB_OUTPUT

      - name: Timeout for Okapi to start
        run: sleep 10

      - name: Pull all module descriptors into Okapi
        uses: fjogeleit/http-request-action@v1
        with:
          url: http://${{ steps.okapi-ip.outputs.ip }}:9130/_/proxy/pull/modules
          method: 'POST'
          contentType: 'application/json; charset=utf-8'
          customHeaders: '{ "Accept": "application/json; charset=utf-8" }'
          data: ${{ inputs.okapi-pull-urls }}
          timeout: 60000

      - name: Download ModuleDescriptor
        uses: actions/download-artifact@v4
        with:
          name: ModuleDescriptor.json

      - name: Post ModuleDescriptor to Okapi
        uses: fjogeleit/http-request-action@v1
        with:
          url: http://${{ steps.okapi-ip.outputs.ip }}:9130/_/proxy/modules
          method: 'POST'
          contentType: 'application/json; charset=utf-8'
          customHeaders: '{ "Accept": "application/json; charset=utf-8" }'
          file: ModuleDescriptor.json
