name: Go report testing variables

on:
  workflow_call:
    inputs:
      artifact-id:
        required: true
        type: string
      artifact-version:
        required: true
        type: string
      is-release:
        required: true
        type: string
      is-main-branch:
        required: true
        type: string
      do-docker-push:
        required: true
        type: string

jobs:
  run:
    name: Report testing variables
    runs-on: ubuntu-latest

    steps:
      - name: Show some variables
        env:
          IS_RELEASE: ${{ inputs.is-release }}
          ARTIFACT_ID: ${{ inputs.artifact-id }}
          ARTIFACT_VERSION: ${{ inputs.artifact-version }}
          DO_DOCKER_PUSH: ${{ inputs.do-docker-push }}
          IS_MAIN_BRANCH: ${{ inputs.is-main-branch }}
        run: |
          echo "is-release=$IS_RELEASE"
          echo "artifact-id=$ARTIFACT_ID"
          echo "artifact-version=$ARTIFACT_VERSION"
          echo "do-docker-push=$DO_DOCKER_PUSH"
          echo "github.ref=$GITHUB_REF"
          echo "is-main-branch=$IS_MAIN_BRANCH"
