name: Go SonarCloud

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true # fails the check if the PR is from a fork

jobs:
  run:
    name: SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Ensure exists sonar properties
        run: test -e "sonar-project.properties"

      - name: Download coverage reports
        uses: actions/download-artifact@v5
        with:
          name: coverage

      - name: Run Sonar scan
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
