name: Go workflows

on:
  workflow_call:
    inputs:
      docker-label-documentation:
        required: false
        type: string
        default: ''
      has-module-descriptor:
        required: false
        type: boolean
        default: true
      module-descriptor-registry:
        required: false
        type: string
        default: https://folio-registry.dev.folio.org
    secrets:
      # these need to be non-required to allow anything here for forks
      # however, the sub-workflows will fail appropriately if these are not present, as applicable
      SONAR_TOKEN:
        required: false
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false
      FOLIO_REGISTRY_USERNAME:
        required: false
      FOLIO_REGISTRY_PASSWORD:
        required: false

jobs:
  set-shared-variables:
    name: Set shared variables
    runs-on: ubuntu-latest
    outputs:
      is-release: ${{ steps.logic.outputs.is-release }}
      is-main-branch: ${{ steps.vars1.outputs.is-main-branch }}
      do-docker-push: ${{ steps.vars2.outputs.do-docker-push }}
      docker-registry: ${{ steps.logic.outputs.docker-registry }}
      artifact-id: ${{ steps.vars1.outputs.artifact-id }}
      repo-description: ${{ steps.vars1.outputs.repo-description }}
    steps:
      - id: logic
        name: Determine default values
        shell: python
        run: |
          import os
          import re

          ref = "${{ github.ref }}"
          print("We are on ref:", ref)
          if re.match(r'^refs/tags/v\d+\..+', ref):
            print("  We are on a tag vX.Y")
            is_release = True
            docker_registry = "folioorg"
          else:
            print("  We are not on a version tag")
            is_release = False
            docker_registry = "folioci"

          output = open(os.environ['GITHUB_OUTPUT'], 'a')
          output.write("is-release=" + str(is_release) + "\n")
          output.write(f"docker-registry={docker_registry}\n")
          output.close()

          output = open(os.environ['GITHUB_ENV'], 'a')
          output.write("IS_RELEASE=" + str(is_release) + "\n")
          output.close()

      - id: vars1
        name: Determine first set of other variables
        run: |
          echo "artifact-id=${GITHUB_REPOSITORY##*/}" | tee -a $GITHUB_OUTPUT
          echo "repo-description=${{ github.event.repository.description }}" | tee -a $GITHUB_OUTPUT
          # On a fork, the default branch might be other:
          if ${{ github.ref == 'refs/heads/main' || github.ref  == 'refs/heads/master' }}; then
            echo "is-main-branch=True" | tee -a $GITHUB_OUTPUT
            echo "IS_MAIN_BRANCH=True" >> $GITHUB_ENV
          else
            echo "is-main-branch=False" | tee -a $GITHUB_OUTPUT
            echo "IS_MAIN_BRANCH=False" >> $GITHUB_ENV
          fi

      - id: vars2
        name: Determine second set of other variables
        run: |
          if ${{ env.IS_RELEASE == 'True' }}; then
            echo "do-docker-push=True" | tee -a $GITHUB_OUTPUT
          else
            if ${{ env.IS_MAIN_BRANCH == 'True' }}; then
              echo "do-docker-push=True" | tee -a $GITHUB_OUTPUT
            else
              echo "do-docker-push=False" | tee -a $GITHUB_OUTPUT
            fi
          fi

  build:
    name: Checkout and build
    needs: [set-shared-variables]
    uses: ./.github/workflows/go-build.yml
    with:
      artifact-id: ${{ needs.set-shared-variables.outputs.artifact-id }}

  version-number:
    needs: [set-shared-variables]
    uses: ./.github/workflows/go-version-number.yml
    with:
      is-release: ${{ needs.set-shared-variables.outputs.is-release }}

  sonarcloud:
    name: SonarCloud analysis
    needs: [build]
    uses: ./.github/workflows/go-sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-publish:
    needs: [set-shared-variables, version-number, build]
    uses: ./.github/workflows/go-docker-publish.yml
    with:
      is-release: ${{ needs.set-shared-variables.outputs.is-release }}
      is-main-branch: ${{ needs.set-shared-variables.outputs.is-main-branch}}
      artifact-id: ${{ needs.set-shared-variables.outputs.artifact-id }}
      artifact-version: ${{ needs.version-number.outputs.version-number }}
      docker-registry: ${{ needs.set-shared-variables.outputs.docker-registry }}
      do-docker-push: ${{ needs.set-shared-variables.outputs.do-docker-push }}
      docker-label-documentation: ${{ inputs.docker-label-documentation }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  generate-module-descriptor:
    name: Generate module descriptor
    needs: [set-shared-variables, version-number]
    uses: ./.github/workflows/go-module-descriptor-generate.yml
    with:
      artifact-id: ${{ needs.set-shared-variables.outputs.artifact-id }}
      artifact-version: ${{ needs.version-number.outputs.version-number }}
      docker-registry: ${{ needs.set-shared-variables.outputs.docker-registry }}

  okapi-dependency-check:
    name: Okapi dependency check
    needs: [set-shared-variables, generate-module-descriptor]
    uses: ./.github/workflows/go-module-descriptor-verify.yml
    with:
      okapi-pull-urls: '{"urls": ["https://folio-registry.dev.folio.org"]}'
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-description:
    name: Publish image description
    needs: [set-shared-variables, generate-module-descriptor, docker-publish]
    if: needs.set-shared-variables.outputs.is-release == 'True' || needs.set-shared-variables.outputs.is-main-branch == 'True'
    uses: ./.github/workflows/docker-description.yml
    with:
      artifact-id: ${{ needs.set-shared-variables.outputs.artifact-id }}
      docker-registry: ${{ needs.set-shared-variables.outputs.docker-registry }}
      repo-description: ${{ needs.set-shared-variables.outputs.repo-description }}
      has-module-descriptor: ${{ inputs.has-module-descriptor }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  publish-module-descriptor:
    name: Publish module descriptor
    needs: [set-shared-variables, generate-module-descriptor, okapi-dependency-check, docker-publish]
    if: needs.set-shared-variables.outputs.is-release == 'True' || needs.set-shared-variables.outputs.is-main-branch == 'True'
    uses: ./.github/workflows/go-module-descriptor-publish.yml
    with:
      module-descriptor-registry: ${{ inputs.module-descriptor-registry }}
    secrets:
      registry-username: ${{ secrets.FOLIO_REGISTRY_USERNAME }}
      registry-password: ${{ secrets.FOLIO_REGISTRY_PASSWORD }}

  report-testing-variables:
    needs: [set-shared-variables, version-number]
    uses: ./.github/workflows/go-report-testing-variables.yml
    with:
      is-release: ${{ needs.set-shared-variables.outputs.is-release }}
      is-main-branch: ${{ needs.set-shared-variables.outputs.is-main-branch}}
      artifact-id: ${{ needs.set-shared-variables.outputs.artifact-id }}
      artifact-version: ${{ needs.version-number.outputs.version-number }}
      do-docker-push: ${{ needs.set-shared-variables.outputs.do-docker-push }}

