name: Gradle Build

on:
  workflow_call:
    inputs:
      gradle-directory:
        description: Directory containing the Gradle project.
        required: true
        type: string
      java-version:
        description: Java version.
        required: true
        type: string
      artifact-id:
        description: Artifact/module name (e.g. mod-agreements).
        required: true
        type: string
      artifact-version:
        description: Final artifact version.
        required: true
        type: string
      docker-registry:
        description: Docker Hub organization.
        required: true
        type: string
      build-command:
        description: Gradle command.
        required: false
        type: string
        default: "assemble"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.gradle-directory }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build Project
        run: |
          ./gradlew \
            ${{ inputs.build-command }} \
            --console plain \
            --no-daemon

      - name: Upload application JAR
        uses: actions/upload-artifact@v7
        with:
          name: built-jars
          path: |
            ${{ inputs.gradle-directory }}/build/libs/*.jar

      # The build does not know the artifact version or the Docker Hub organization.
      - name: Update ModuleDescriptor identifiers
        env:
          MODULE_ID: ${{ inputs.artifact-id }}-${{ inputs.artifact-version }}
          DOCKER_IMAGE: ${{ inputs.docker-registry }}/${{ inputs.artifact-id }}:${{ inputs.artifact-version }}
        run: |
          MD=build/resources/main/okapi/ModuleDescriptor.json
          if [[ ! -f "$MD" ]]; then
            echo "No ModuleDescriptor found."
            exit 0
          fi
          mv "$MD" "$MD.orig"
          jq --arg id "$MODULE_ID" --arg image "$DOCKER_IMAGE" \
            '.id |= $id | if has("launchDescriptor") then
              .launchDescriptor.dockerImage |= $image |
              .launchDescriptor.dockerPull |= "true" else . end' \
            "$MD.orig" > "$MD"

      - name: Upload ModuleDescriptor
        uses: actions/upload-artifact@v7
        with:
          name: ModuleDescriptor.json
          path: |
            ${{ inputs.gradle-directory }}/build/resources/main/okapi/ModuleDescriptor.json
