name: Gradle Build

on:
  workflow_call:
    inputs:
      gradle-directory:
        description: Directory containing the Gradle project.
        required: false
        type: string
        default: service
      java-version:
        description: Java version.
        required: false
        type: string
        default: "17"
      build-command:
        description: Gradle command.
        required: false
        type: string
        default: "assemble"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.gradle-directory }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build Project
        run: |
          ./gradlew \
            ${{ inputs.build-command }} \
            --console plain \
            --no-daemon

      - name: Upload application JAR
        uses: actions/upload-artifact@v7
        with:
          name: built-jars
          path: |
            ${{ inputs.gradle-directory }}/build/libs/*.jar

      - name: Upload ModuleDescriptor
        uses: actions/upload-artifact@v7
        with:
          name: ModuleDescriptor.json
          path: |
            ${{ inputs.gradle-directory }}/build/resources/main/okapi/ModuleDescriptor.json