name: Gradle Backend Module

on:
  workflow_call:
    inputs:
      artifact-id:
        description: Artifact/module name (e.g. mod-agreements).
        required: true
        type: string

      gradle-directory:
        description: Directory containing the Gradle project.
        required: false
        default: service
        type: string

      module-descriptor-registry:
        description: Okapi ModuleDescriptor registry URL.
        required: true
        default: https://folio-registry.dev.folio.org
        type: string

      docker-health-command:
        description: Docker health check command.
        required: false
        default: ""
        type: string

      docker-label-documentation:
        description: OCI documentation label.
        required: false
        default: ""
        type: string

    secrets:
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true
      registry-username:
        required: true
      registry-password:
        required: true

# Determine Gradle version
jobs:
  get-gradle-version:
    name: Determine Gradle Version
    uses: ./.github/workflows/get-gradle-version.yml
    with:
      gradle-directory: ${{ inputs.gradle-directory }}

# Build metadata
  metadata:
    name: Build Metadata
    needs:
      - get-gradle-version
    uses: ./.github/workflows/build-metadata.yml
    with:
      gradle-version: ${{ needs.get-gradle-version.outputs.gradle-version }}

# Build application
  gradle-build:
    name: Gradle Build
    needs:
      - metadata
    uses: ./.github/workflows/gradle-build.yml
    with:
      gradle-directory: ${{ inputs.gradle-directory }}
      artifact-version: ${{ needs.metadata.outputs.artifact-version }}

# Dependency submission
  dependency-submission:
    name: Dependency Submission
    needs:
      - gradle-build
    uses: ./.github/workflows/dependency-submission.yml
    with:
      gradle-directory: ${{ inputs.gradle-directory }}

# Docker build
  docker-build:
    name: Docker Build
    needs:
      - metadata
      - gradle-build
    uses: ./.github/workflows/docker-build.yml
    with:
      artifact-id: ${{ inputs.artifact-id }}
      artifact-version: ${{ needs.metadata.outputs.artifact-version }}
      docker-registry: ${{ needs.metadata.outputs.docker-registry }}
      docker-health-command: ${{ inputs.docker-health-command }}
      docker-label-documentation: ${{ inputs.docker-label-documentation }}
      do-docker-push: ${{ fromJSON(needs.metadata.outputs.do-docker-push) }}

    secrets:
      dockerhub-username: ${{ secrets.dockerhub-username }}
      dockerhub-token: ${{ secrets.dockerhub-token }}

# Publish ModuleDescriptor
  publish-module-descriptor:
    name: Publish ModuleDescriptor
    if: needs.metadata.outputs.do-docker-push == 'true'
    needs:
      - metadata
      - docker-build
    uses: ./.github/workflows/publish-module-descriptor.yml
    with:
      module-descriptor-registry: ${{ inputs.module-descriptor-registry }}

    secrets:
      registry-username: ${{ secrets.registry-username }}
      registry-password: ${{ secrets.registry-password }}