name: Docker Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

      docker-organization:
        required: true
        type: string

      version:
        required: true
        type: string

jobs:

  docker-build:

    runs-on: ubuntu-latest

    timeout-minutes: 20

    permissions:
      contents: read

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download application JAR
        uses: actions/download-artifact@v4
        with:
          name: gradle-jar
          path: service/build/libs

      - name: Build Docker image
        run: |
          IMAGE=${{ inputs.docker-organization }}/${{ inputs.image-name }}:${{ inputs.version }}

          docker build \
            -t "$IMAGE" \
            .

      - name: Export Docker image
        run: |
          IMAGE=${{ inputs.docker-organization }}/${{ inputs.image-name }}:${{ inputs.version }}

          docker save "$IMAGE" \
            -o docker-image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker-image.tar