name: test

on: workflow_call

jobs:
  inner1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

  inner2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
