name: FOLIO UI Install Packages

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use, in semver notation.
          Examples include 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
        required: false
        type: string
        default: "20.x"
      folio-npm-registry:
        description: Full URL to the registry to use for @folio modules.
          Defaults to "https://repository.folio.org/repository/npm-folioci/"
        required: false
        type: string
        default: "https://repository.folio.org/repository/npm-folioci/"
      debug-yarn-packages:
        description: Whether to print all packages installed by yarn. Defaults to "false"
        required: false
        type: boolean
        default: false

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false # spammy

      - uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
          check-latest: true
          always-auth: true

      - name: Set FOLIO NPM registry
        run: yarn config set @folio:registry ${{inputs.folio-npm-registry}}

      - name: Install dependencies
        run: yarn install --ignore-scripts --non-interactive

      - name: List installed FOLIO package versions
        run: yarn list --pattern @folio

      - name: List all installed package versions (enable via debug-yarn-packages)
        if: ${{inputs.debug-yarn-packages}}
        run: yarn list
