name: testinner

on: workflow_call

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          check-latest: true
          always-auth: true
