name: FOLIO UI Install Packages

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use, in semver notation
        required: true
        type: string
      folio-npm-registry:
        description: Full URL to the registry to use for @folio modules.
          Defaults to "https://repository.folio.org/repository/npm-folioci/"
        required: true
        type: string
      debug-yarn-packages:
        description: Whether to print all packages installed by yarn. Defaults to "false"
        required: false
        type: boolean
        default: false
    outputs:
      cache-key:
        description: Actions cache key to use for caching node_modules and yarn.lock. Derived from yarn.lock hash
        value: ${{ jobs.install.outputs.cache-key }}
jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest

    outputs:
      cache-key: ${{ steps.get-cache-key.outputs.key }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false # spammy

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          check-latest: true
          always-auth: true

      - name: Set FOLIO NPM registry
        run: yarn config set @folio:registry ${{ inputs.folio-npm-registry }}

      - name: Install dependencies
        run: yarn install --ignore-scripts --non-interactive

      - name: List installed FOLIO package versions
        run: yarn list --pattern @folio

      - name: List all installed package versions (enable via debug-yarn-packages)
        if: ${{ inputs.debug-yarn-packages }}
        run: yarn list

      - id: get-cache-key
        name: Calculate cache key
        run: echo key=node-modules-${{ hashFiles('**/yarn.lock') }} | tee -a $GITHUB_OUTPUT

      - name: Cache node_modules and yarn.lock
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            yarn.lock
          key: ${{ steps.get-cache-key.outputs.key }}
