name: FOLIO UI Unit Tests (Jest)

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use, in semver notation
        required: true
        type: string
      folio-npm-registry:
        description: Full URL to the registry to use for @folio modules
        required: true
        type: string
      jest-test-command:
        description: Command to run Jest tests
        required: true
        type: string
      jest-junit-output-dir:
        description: Directory in which Jest reports are stored in
        required: true
        type: string
      jest-coverage-report-dir:
        description: Directory in which Jest coverage reports are stored in
        required: true
        type: string

jobs:
  run:
    name: Run Jest tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false # spammy

      - name: Install Node ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          check-latest: true
          always-auth: true

      - name: Set FOLIO NPM registry
        run: yarn config set @folio:registry ${{ inputs.folio-npm-registry }}

      - name: Install dependencies
        run: yarn install --ignore-scripts --non-interactive

      - name: Run Jest tests
        run: ${{ inputs.jest-test-command }}
        env:
          # needed for projects that do not specify in package.json
          # see https://github.com/jest-community/jest-junit?tab=readme-ov-file#configuration
          JEST_JUNIT_OUTPUT_DIR: ${{ inputs.jest-junit-output-dir }}

      - name: tree
        run: ls -R artifacts

      - name: treee
        run: tree artifacts

      - name: Publish Jest unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() }}
        with:
          check_name: Jest Unit Test Results
          files: "${{ inputs.jest-junit-output-dir }}/*.xml"

      - name: Publish Jest coverage report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: jest-coverage-report
          path: ${{ inputs.jest-coverage-report-dir }}
          retention-days: 5

      - name: Publish yarn.lock
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: yarn.lock
          path: yarn.lock
          retention-days: 1
