name: FOLIO UI Generate Module Descriptor

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      folio-npm-registry:
        required: true
        type: string
      package-version:
        required: true
        type: string

jobs:
  run:
    name: Generate module descriptor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false # spammy

      - name: Install Node ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          check-latest: true
          always-auth: true

      - name: Enable corepack
        run: corepack enable

      - name: Set FOLIO NPM registry
        run: yarn config set npmScopes.folio.npmRegistryServer ${{ inputs.folio-npm-registry }}

      # note that we use `npm pkg set version` instead of `yarn version` here.
      # tldr: https://github.com/yarnpkg/berry/issues/4548
      # long version: 'yarn version' does a lot of work installing dependencies
      # (which we are explicitly trying to avoid), and interacting with git in
      # a way I don't totally understand but which leads to an error:
      #   Usage Error: No ancestor could be found between any of HEAD and
      #   master, origin/master, upstream/master, main, origin/main,
      #   upstream/main
      # Anyway. We just want to tweak the version in `package.json` and we can
      # do that with `npm pkg`, so we do.
      - name: Set package version number to ${{ inputs.package-version }}
        run: |-
          npm pkg set version=${{ inputs.package-version }}

      - name: Generate module descriptor
        run: |-
          rm .stripesclirc.js
          yarn dlx -q @folio/stripes-cli mod descriptor --full --strict | jq '.[]' > module-descriptor.json

      - name: Print module descriptor
        run: cat module-descriptor.json

      # we publish it to the registry as a separate job
      - name: Upload module descriptor as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: module-descriptor.json
          path: module-descriptor.json
