name: FOLIO UI Workflows

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use, in semver notation
          Examples include 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
        required: true
        type: string
        default: "18.x"

jobs:
  innerinner:
    uses: ./.github/workflows/ui-innerinner1.yml

  inner1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1
        run: node -v

  inner2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step2
        run: node -v

  inner3:
    needs: inner1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          check-latest: true
          always-auth: true

  inner4:
    needs: [innerinner, inner2, inner3]
    runs-on: ubuntu-latest
    steps:
      - name: my-step4
        run: node -v
