name: FOLIO UI Workflows

on:
  workflow_call:
    inputs:
      # node/yarn configuration
      node-version:
        description: Node version to use, in semver notation.
          Examples include 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
        required: false
        type: string
        default: "20.x"
      folio-npm-registry:
        description: Full URL to the registry to use for @folio modules.
          Defaults to "https://repository.folio.org/repository/npm-folioci/"
        required: false
        type: string
        default: "https://repository.folio.org/repository/npm-folioci/"
      debug-yarn-packages:
        description:
          Whether to print all packages installed by yarn and force publish yarn.lock.
          This should not be enabled except during debugging. Defaults to false
        required: false
        type: boolean
        default: false

      # linting
      allow-lint-errors:
        description: Whether to allow lint errors; if false, errors will fail the build. Defaults to true
        required: false
        type: boolean
        default: true

      # unit tests (Jest)
      jest-enabled:
        description: Whether to run Jest tests. Defaults to true
        required: false
        type: boolean
        default: true
      jest-test-command:
        description: Command to run Jest tests. Defaults to "yarn test"
        required: false
        type: string
        default: yarn test
      jest-junit-output-dir:
        description:
          Directory in which Jest reports are stored in, without trailing slash.
          Defaults to "artifacts/jest-junit"
        required: false
        type: string
        default: artifacts/jest-junit
      jest-coverage-report-dir:
        description:
          Directory in which Jest coverage reports are stored in, with trailing slash.
          Defaults to "artifacts/coverage-jest/lcov-report/"
        required: false
        type: string
        default: artifacts/coverage-jest/lcov-report/

      # unit tests (Bigtest)
      bigtest-enabled:
        description: Whether to run Bigtest tests. Defaults to false
        required: false
        type: boolean
        default: false
      bigtest-test-command:
        description: Command to run Bigtest tests. Defaults to "yarn test"
        required: false
        type: string
        default: yarn test
      bigtest-junit-output-dir:
        description:
          Directory in which Bigtest reports are stored in, without trailing slash.
          Defaults to "artifacts/runTest"
        required: false
        type: string
        default: artifacts/runTest
      bigtest-coverage-report-dir:
        description:
          Directory in which Jest coverage reports are stored in, with trailing slash.
          Defaults to "artifacts/coverage/lcov-report/"
        required: false
        type: string
        default: artifacts/coverage/lcov-report/

      # translations
      compile-translations:
        description: Whether to compile translation files. Defaults to true
        required: false
        type: boolean
        default: true

jobs:
  # this job is responsible for printing install information and publishing yarn.lock if debug is enabled
  install-and-lint:
    uses: ./.github/workflows/ui-install-and-lint.yml
    with:
      node-version: ${{ inputs.node-version }}
      folio-npm-registry: ${{ inputs.folio-npm-registry }}
      allow-lint-errors: ${{ inputs.allow-lint-errors }}
      debug-yarn-packages: ${{ inputs.debug-yarn-packages }}

  jest-tests:
    name: Run Jest tests
    uses: ./.github/workflows/ui-tests-jest.yml
    if: ${{ inputs.jest-enabled }}
    with:
      node-version: ${{ inputs.node-version }}
      folio-npm-registry: ${{ inputs.folio-npm-registry }}
      jest-test-command: ${{ inputs.jest-test-command }}
      jest-junit-output-dir: ${{ inputs.jest-junit-output-dir }}
      jest-coverage-report-dir: ${{ inputs.jest-coverage-report-dir }}

  bigtest-tests:
    name: Run Bigtest tests
    uses: ./.github/workflows/ui-tests-bigtest.yml
    if: ${{ inputs.bigtest-enabled }}
    with:
      node-version: ${{ inputs.node-version }}
      folio-npm-registry: ${{ inputs.folio-npm-registry }}
      bigtest-test-command: ${{ inputs.bigtest-test-command }}
      bigtest-junit-output-dir: ${{ inputs.bigtest-junit-output-dir }}
      bigtest-coverage-report-dir: ${{ inputs.bigtest-coverage-report-dir }}

  translations:
    uses: ./.github/workflows/ui-translations.yml
    if: ${{ inputs.compile-translations }}
    with:
      node-version: ${{ inputs.node-version }}
      folio-npm-registry: ${{ inputs.folio-npm-registry }}

  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: "check if GITHUB_TOKEN exists"
        env:
          super_secret: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ env.super_secret == '' }}
        run: 'echo "echo the secret \"GITHUB_TOKEN\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it"'

  version-number:
    uses: ./.github/workflows/ui-version-number.yml
