name: FOLIO UI Workflows

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use, in semver notation.
          Examples include 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
        required: false
        type: string
        default: "20.x"
      folio-npm-registry:
        description: Full URL to the registry to use for @folio modules.
          Defaults to "https://repository.folio.org/repository/npm-folioci/"
        required: false
        type: string
        default: "https://repository.folio.org/repository/npm-folioci/"
      debug-yarn-packages:
        description: Whether to print all packages installed by yarn. Defaults to "false"
        required: false
        type: boolean
        default: false

jobs:
  version-number:
    name: Get version number
    uses: ./.github/workflows/ui-version-number.yml

  install:
    uses: ./.github/workflows/ui-install.yml

  inner2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step2
        run: node -v

  inner3:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1
        run: node -v

  inner4:
    needs: [inner2, inner3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          check-latest: true
          always-auth: true
      - name: my-step4
        run: node -v
